#!/bin/bash

set -eux

# convert storm.properties to storm.yaml and set STORM_CONF_DIR to point to the
# directory containing it

bash scripts/config "$PWD"

case "$1" in
nimbus|supervisor|ui|drpc|logviewer)
    export STORM_CONF_DIR="$PWD"
    exec "$CDH_STORM_HOME/bin/storm" "$1"
    ;;
*)
    echo "Unknown service: $1" >&2
    exit 1
    ;;
esac
