#!/bin/bash

set -eu

# convert storm.properties to storm.yaml and set STORM_CONF_DIR to point to the
# directory containing it

case "$1" in
nimbus|supervisor|ui|drpc|logviewer)
    exec "$CDH_STORM_HOME/bin/storm" "$1"
    ;;
*)
    echo "Unknown service: $1" >&2
    exit 1
    ;;
esac
